/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as PolosRouteImport } from './routes/polos'
import { Route as IndexRouteImport } from './routes/index'

const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PolosRoute = PolosRouteImport.update({
  id: '/polos',
  path: '/polos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/polos': typeof PolosRoute
  '/programacao': typeof ProgramacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/polos': typeof PolosRoute
  '/programacao': typeof ProgramacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/polos': typeof PolosRoute
  '/programacao': typeof ProgramacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/polos' | '/programacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/polos' | '/programacao'
  id: '__root__' | '/' | '/polos' | '/programacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolosRoute: typeof PolosRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polos': {
      id: '/polos'
      path: '/polos'
      fullPath: '/polos'
      preLoaderRoute: typeof PolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolosRoute: PolosRoute,
  ProgramacaoRoute: ProgramacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
