/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as PolosRouteImport } from './routes/polos'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as AtracoesRouteImport } from './routes/atracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoloIdRouteImport } from './routes/polo.$id'

const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PolosRoute = PolosRouteImport.update({
  id: '/polos',
  path: '/polos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const AtracoesRoute = AtracoesRouteImport.update({
  id: '/atracoes',
  path: '/atracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoloIdRoute = PoloIdRouteImport.update({
  id: '/polo/$id',
  path: '/polo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atracoes': typeof AtracoesRoute
  '/mapa': typeof MapaRoute
  '/polos': typeof PolosRoute
  '/programacao': typeof ProgramacaoRoute
  '/polo/$id': typeof PoloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atracoes': typeof AtracoesRoute
  '/mapa': typeof MapaRoute
  '/polos': typeof PolosRoute
  '/programacao': typeof ProgramacaoRoute
  '/polo/$id': typeof PoloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atracoes': typeof AtracoesRoute
  '/mapa': typeof MapaRoute
  '/polos': typeof PolosRoute
  '/programacao': typeof ProgramacaoRoute
  '/polo/$id': typeof PoloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atracoes'
    | '/mapa'
    | '/polos'
    | '/programacao'
    | '/polo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atracoes' | '/mapa' | '/polos' | '/programacao' | '/polo/$id'
  id:
    | '__root__'
    | '/'
    | '/atracoes'
    | '/mapa'
    | '/polos'
    | '/programacao'
    | '/polo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtracoesRoute: typeof AtracoesRoute
  MapaRoute: typeof MapaRoute
  PolosRoute: typeof PolosRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  PoloIdRoute: typeof PoloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polos': {
      id: '/polos'
      path: '/polos'
      fullPath: '/polos'
      preLoaderRoute: typeof PolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atracoes': {
      id: '/atracoes'
      path: '/atracoes'
      fullPath: '/atracoes'
      preLoaderRoute: typeof AtracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polo/$id': {
      id: '/polo/$id'
      path: '/polo/$id'
      fullPath: '/polo/$id'
      preLoaderRoute: typeof PoloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtracoesRoute: AtracoesRoute,
  MapaRoute: MapaRoute,
  PolosRoute: PolosRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  PoloIdRoute: PoloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
